service: fibb-ai-marketplace

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    PRODUCTS_TABLE: ${self:service}-products-${self:provider.stage}

functions:
  getProducts:
    handler: src/handlers/products.getProductsHandler
    events:
      - http:
          path: products
          method: get
  createProduct:
    handler: src/handlers/products.createProductHandler
    events:
      - http:
          path: products
          method: post

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
  - serverless-offline
